apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo-microservice-configurator
  namespace: argo-events-eventbus
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    demo-microservice-event:
      owner: "gepaplexx-demos"
      repository: "demo-microservice"
      webhook:
        endpoint: "/event"
        port: "12000"
        method: "POST"
      events:
        - "push"
        - "create"
        - "delete"
      webhookSecret:
        name: workflow-demo-microservice
        key: webhook-secret
      insecure: false
      active: true