apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: git-operations
spec:
  workflowMetadata:
    labels:
      app: argo
      clusterworkflowtemplate: git-operations
  templates:
    - name: checkout
      metadata:
        labels:
          template: checkout
      container:
        name: git-workflows
        image: ghcr.io/gepaplexx/go-git-workflows:latest
        command:
          - "git-workflows"
        args:
          - checkout
          - --url
          - '{{ workflow.parameters.repository }}'
          - --branch
          - '{{ workflow.parameters.branch }}'
          - --name
          - '{{ workflow.parameters.reponame }}'
        volumeMounts:
          - name: workspace
            mountPath: /mnt/out/
          - name: pipeline-secrets
            mountPath: /workflow/.ssh/known_hosts
            subPath: known_hosts
          - name: pipeline-secrets
            mountPath: /workflow/.ssh/id_rsa
            subPath: id_rsa
      metrics:
        prometheus:
          - name: duration_task_seconds
            help: "Duration gauge by task name in seconds - task level"
            labels:
              - key: "task_name"
                value: "checkout"
              - key: "application"
                value: "{{ workflow.parameters.reponame }}"
              - key: "branch"
                value: "{{ workflow.parameters.branch }}"
              - key: "commit_user"
                value: "{{ workflow.parameters.commit-user }}"
              - key: "commit_email"
                value: "{{ workflow.parameters.commit-email }}"
              - key: status
                value: "{{ status }}"
            gauge:
              realtime: false
              value: "{{ duration }}"
          - name: result_task_counter
            help: "Count of task execution by result status  - task level"
            labels:
              - key: "task_name"
                value: "checkout"
              - key: "application"
                value: "{{ workflow.parameters.reponame }}"
              - key: "branch"
                value: "{{ workflow.parameters.branch }}"
              - key: "commit_user"
                value: "{{ workflow.parameters.commit-user }}"
              - key: "commit_email"
                value: "{{ workflow.parameters.commit-email }}"
              - key: status
                value: "{{ status }}"
              - key: "id"
                value: "{{ workflow.uid }}"
            counter:
              value: "1"