apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: workflow-configurator-gitlab
spec:
  entrypoint: configure
  arguments:
    parameters:
      - name: event
        value: comes-from-caller
  serviceAccountName: operate-workflow-sa
  workflowMetadata:
    labels:
      app: argo
      clusterworkflowtemplate: workflow-configurator-gitlab
  templates:
    - name: configure
      dag:
        tasks:
          - name: read-event
            templateRef:
              name: configuration-operations
              clusterScope: true
              template: read-event
          - name: configure-workflow
            depends: "read-event"
            templateRef:
              name: workflow-wf-configurator
              clusterScope: true
              template: configure-workflow
            arguments:
              parameters:
                - name: event-type
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.event_name')}}"
                - name: repository
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.repository.git_ssh_url')}}"
                - name: reponame
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.repository.name')}}"
                - name: branch
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.ref')}}"
                - name: commit-hash
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.checkout_sha') }}"
                - name: commit-email
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.commits[0].author.email')}}"
                - name: commit-user
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.commits[0].author.name')}}"
                - name: commit-url
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.commits[0].url')}}"
                - name: create-delete-sender
                  value: "{{=jsonpath(tasks['read-event'].outputs.result, '$.user_username')}}"
                - name: deleted # required for GitHub not for GitLab
                  value: "false"


